USE [master]
GO

/****** Object:  Database [godown]    Script Date: 08/11/2017 13:30:44 ******/
CREATE DATABASE [godown] ON  PRIMARY 
( NAME = N'godown', FILENAME = N'D:\Program Files\SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\godown.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'godown_log', FILENAME = N'D:\Program Files\SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\godown_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [godown] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [godown].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [godown] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [godown] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [godown] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [godown] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [godown] SET ARITHABORT OFF 
GO

ALTER DATABASE [godown] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [godown] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [godown] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [godown] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [godown] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [godown] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [godown] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [godown] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [godown] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [godown] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [godown] SET  DISABLE_BROKER 
GO

ALTER DATABASE [godown] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [godown] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [godown] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [godown] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [godown] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [godown] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [godown] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [godown] SET  READ_WRITE 
GO

ALTER DATABASE [godown] SET RECOVERY FULL 
GO

ALTER DATABASE [godown] SET  MULTI_USER 
GO

ALTER DATABASE [godown] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [godown] SET DB_CHAINING OFF 
GO


